#!/usr/bin/env bash
# todo

DATE="2018-07-24"
RAW_DATA_ROOT="/data3/rawData/riskModelAuto"
RAW_DATA_ROOT_WITH_DATA=${RAW_DATA_ROOT}"/"${DATE}
HDFS_HOST="hdfs://localhost:9000"

HDFS_RISK_MODEL_AUTO_ROOT="/hdfs/riskModelAuto"
HDFS_RISK_MODEL_AUTO_ROOT_WITH_DATA=${HDFS_RISK_MODEL_AUTO_ROOT}"/"${DATE}
hadoop fs -put RAW_DATA_ROOT_WITH_DATA ${HDFS_HOST}${HDFS_RISK_MODEL_AUTO_ROOT_WITH_DATA}
